# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31fa61f26a4c96bcd706a34f7dac1c1c14382a1a8a447c983b0645ad3cfc5f954592abf92704ce646ab350596835673af29b3473c74d1f11209d5b06d99ee37d

test:
  secret_key_base: 9e2038907f9ff41e11290d16a12e0d00af6b87115cf1eb7e2c2bd4601504d6a304457cad2bfe5ac6e7332872c484b76023ecedabc3d0ad8531bdfdb465f2bf9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
